CREATE TABLE IF NOT EXISTS category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS events
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title             VARCHAR(255)                            NOT NULL,
    annotation        VARCHAR(255),
    description       VARCHAR(500),
    createdOn         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    eventDate         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    publishedOn       TIMESTAMP WITHOUT TIME ZONE,
    paid              BOOLEAN,
    requestModeration BOOLEAN,
    state             VARCHAR(255)                            NOT NULL,
    participantLimit  INT,
    categoryId        BIGINT,
    initiator         BIGINT                                  NOT NULL,
    longitude         REAL,
    latitude          REAL,
    CONSTRAINT pk_event PRIMARY KEY (id),
    CONSTRAINT FK_EVENT_ON_OWNER FOREIGN KEY (initiator) REFERENCES users (id),
    CONSTRAINT FK_EVENT_ON_CATEGORY FOREIGN KEY (categoryId) REFERENCES category (id)
);

CREATE TABLE IF NOT EXISTS compilation
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title  VARCHAR(255)                            NOT NULL,
    pinned BOOLEAN,
    CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilation_events
(
    compilationId BIGINT NOT NULL,
    eventId       BIGINT NOT NULL,
    CONSTRAINT pk_compilation_events PRIMARY KEY (compilationId, eventId),
    CONSTRAINT FK_CE_ON_COMPILATION FOREIGN KEY (compilationId) REFERENCES compilation (id),
    CONSTRAINT FK_CE_ON_EVENT FOREIGN KEY (eventId) REFERENCES events (id)
);

CREATE TABLE IF NOT EXISTS participation_request
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    event     BIGINT                                  NOT NULL,
    requester BIGINT                                  NOT NULL,
    status    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_participation_request PRIMARY KEY (id),
    CONSTRAINT FK_PR_ON_EVENT FOREIGN KEY (event) REFERENCES events (id),
    CONSTRAINT FK_PR_ON_USER FOREIGN KEY (requester) REFERENCES users (id)
);

